### ISSUE TITLE
code-freeze gets applied to build repo master branches regardless of pull_request_target filter

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/.github#121]
The build repos code-freeze yml tries to filter and only freeze the release branches using the following logic:
```
on:
  pull_request_target:
    branches: [ "v[0-9]+.[0-9]+.[0-9]+" ]
  issue_comment:
    types: [created]
```
however, this does not work, because the branches filter is only on the pull_request_target events, as soon as an "issue_comment" occurs the code_freeze is called, and "issue_comment" has no branch metadata and so cannot be filtered in the same way.

A more generic branch check logic needs to be used to obtain the pull request branch object directly for issue comment events, and verify the target branch matches the required branches to freeze.
